# simple basex
services:
  basex:
    image: quodatum/basexhttp
    container_name: basex
    ports:
      - "9091:8080"
    volumes:
      - basex-data:/srv/basex/data 
      - ./root.xqm:/srv/basex/webapp/restxq.xqm 
    restart: unless-stopped
volumes:
  basex-data: