# simple basex
version: '3'
services:
  basex:
    image: quodatum/basexhttp:15-jre-hotspot
    container_name: basex
    ports:
      - "8984:8984"
    volumes:
      - ./custom:/srv/basex/lib/custom:ro
