# multi-arch docker build
name: multi-arch docker buildx
env:
    JDK_IMAGE: adoptopenjdk:11-jre-hotspot
    BASEX_VER: https://files.basex.org/releases/9.5/BaseX95.zip
on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: quodatum/basexhttp:latest,quodatum/basexhttp:BaseX95.zip,quodatum/basexhttp:11-jre-hotspot
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}