# multi-arch BaseX docker build
# platforms: linux/amd64,linux/arm/v7,linux/arm64
# publishes to: DockerHub, github
# @see https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages

name: multi-arch docker buildx
env:
    JDK_IMAGE: adoptopenjdk:11-jre-hotspot
    JDK_TAG: 11-jre-hotspot
    BASEX_VER: https://files.basex.org/releases/9.5.2/BaseX952.zip
    BASEX_TAG: BaseX952
    
on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Build and push to dockerhub
        id: dockerhub_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          build-args: |
            JDK_IMAGE=${{ env.JDK_IMAGE }}
            BASEX_VER=${{ env.BASEX_VER }}
          tags: |
            quodatum/basexhttp:latest
            quodatum/basexhttp:${{ env.JDK_TAG }}
            quodatum/basexhttp:${{ env.BASEX_TAG }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
            registry: docker.pkg.github.com
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
           
      - name: Build and push to github
        id: github_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          build-args: |
            JDK_IMAGE=${{ env.JDK_IMAGE }}
            BASEX_VER=${{ env.BASEX_VER }}
          tags: |
            docker.pkg.github.com/quodatum/basexhttp:latest
            docker.pkg.github.com/quodatum/basexhttp:${{ env.JDK_TAG }}
            docker.pkg.github.com/quodatum/basexhttp:${{ env.BASEX_TAG }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}