# This is a basic workflow to help you get started with Actions

- name: "Docker Setup Buildx"
  # You may pin to the exact commit or the version.
  # uses: docker/setup-buildx-action@2a4b53665e15ce7d7049afb11ff1f70ff1610609
  uses: docker/setup-buildx-action@v1.1.2
  with:
    # Buildx version. (eg. v0.3.0)
    version: # optional
    # Sets the builder driver to be used
    driver: # optional, default is docker-container
    # List of additional driver-specific options. (eg. image=moby/buildkit:master)
    driver-opts: # optional
    # Flags for buildkitd daemon
    buildkitd-flags: # optional, default is --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
    # Sets up docker build command as an alias to docker buildx
    install: # optional, default is false
    # Switch to this builder instance
    use: # optional, default is true
    # Optional address for docker socket or context from `docker context ls`
    endpoint: # optional
